language: go
go:
- 1.20

env:
  global:
    - CC=clang
    - CXX=clang
    - CGO_CXXFLAGS="-std=c++17 -stdlib=libstdc++-9-dev:amd64"

before_install:
- go install -v github.com/mattn/goveralls@latest
# - wget https://apt.llvm.org/llvm.sh
# - chmod +x llvm.sh
# - sudo ./llvm.sh 13
# - sudo apt-get install clang-13
# - sudo apt install libc++-13-dev libc++abi-13-dev
# - export PATH="/usr/bin/:$PATH"
- sudo apt-get update
- sudo apt-get install build-essential
# - which clang
# - which clang-14
# - clang++ --version
# - clang --version
# - clang-14 --version
# - dpkg --list | grep libst
- go get -v -t ./...

script:
- go get -u ./...
# - go vet -v ./...
- go build ./...
- go test ./... -v -coverprofile=_coverage.cov
- go test ./... -race

after_success:
# Note: Do this in the after_success stage so that
# a broken coveralls won't cause the build to fail.
- $HOME/gopath/bin/goveralls -coverprofile=_coverage.cov -service=travis-ci