language: go
go:
- 1.20
dist: bionic

env:
  global:
    - CC=clang
    - CXX=clang++

before_install:
- go install -v github.com/mattn/goveralls@latest
- sudo apt-get update
- sudo apt-get install build-essential
# - wget https://apt.llvm.org/llvm.sh
# - chmod +x llvm.sh
# - sudo ./llvm.sh 10
# - sudo apt-get install clang-10
- clang --version
- clang++ --version
- go get -v -t ./...

script:
- go get -u ./...
- go vet ./...
- go build ./...
- go test ./... -v -coverprofile=_coverage.cov
- go test ./... -race

after_success:
# Note: Do this in the after_success stage so that
# a broken coveralls won't cause the build to fail.
- $HOME/gopath/bin/goveralls -coverprofile=_coverage.cov -service=travis-ci