language: go
go:
- 1.20
dist: focal

env:
  global:
    - CC=clang
    - CXX=clang++

addons
  apt:
    sources:
      - llvm-toolchain-focal
    packages:
      - clang-14

before_install:
- go install -v github.com/mattn/goveralls@latest
- wget https://apt.llvm.org/llvm.sh
- chmod +x llvm.sh
- sudo ./llvm.sh 14
- sudo apt-get update
- sudo apt-get install clang-14
- export PATH=$PWD/clang-14/bin/:$PATH
- clang --version
- go get -v -t ./...

script:
- go get -u ./...
- go vet ./...
- go build ./...
- go test ./... -v -coverprofile=_coverage.cov
- go test ./... -race

after_success:
# Note: Do this in the after_success stage so that
# a broken coveralls won't cause the build to fail.
- $HOME/gopath/bin/goveralls -coverprofile=_coverage.cov -service=travis-ci