timeout: 1800s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

steps:
- name: gcr.io/cloud-builders/docker
  id: "Build the autoloader docker image"
  args: [
    "build",
      "-t", "gcr.io/$PROJECT_ID/autoloader:${COMMIT_SHA}",
      "-f", "Dockerfile", "."
  ]

- name: gcr.io/cloud-builders/docker
  id: "Push the docker container to gcr.io"
  args: [
    "push", "gcr.io/$PROJECT_ID/autoloader:${COMMIT_SHA}",
  ]

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy the autoloader"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{COMMIT_SHA}}/'${COMMIT_SHA}'/' \
           -e 's/{{PROJECT_ID}}/'${PROJECT_ID}'/' \
           -e 's/{{MLAB_BUCKET}}/'$_MLAB_BUCKET'/' \
           -e 's/{{BUCKETS}}/'$_BUCKETS'/' \
           k8s/autoloader.yaml
    /builder/kubectl.bash apply -f k8s/autoloader.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy $FREQUENCY job"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's/{{AUTOLOADER_CRON_SCHEDULE}}/0 *\/3 * * */' \
        -e 's/{{LOAD_PERIOD}}/daily/' \
        k8s/autoloader-cronjob.yaml.template > autoloader-$FREQUENCY-cronjob.yaml
    /builder/kubectl.bash apply -f autoloader-$FREQUENCY-cronjob.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing
  - FREQUENCY=hourly

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy $FREQUENCY job"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's/{{AUTOLOADER_CRON_SCHEDULE}}/0 0 * * 0/' \
        -e 's/{{LOAD_PERIOD}}/monthly/' \
        k8s/autoloader-cronjob.yaml.template > autoloader-$FREQUENCY-cronjob.yaml
    /builder/kubectl.bash apply -f autoloader-$FREQUENCY-cronjob.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing
  - FREQUENCY=weekly

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy $FREQUENCY job"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's/{{AUTOLOADER_CRON_SCHEDULE}}/0 0 1 * */' \
        -e 's/{{LOAD_PERIOD}}/annually/' \
        k8s/autoloader-cronjob.yaml.template > autoloader-$FREQUENCY-cronjob.yaml
    /builder/kubectl.bash apply -f autoloader-$FREQUENCY-cronjob.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing
  - FREQUENCY=monthly
