timeout: 3600s

options:
  env:
  - CXX=clang++
  - CGO_ENABLED=1

steps:

- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - -c
  - |
    docker run -w /go/src/github.com/m-lab/autoloader -v $$GOPATH/pkg/mod:/go/pkg/mod -v $$PWD:/go/src/github.com/m-lab/autoloader cristinaleonr/autoloader:0 sh -c "go vet -v ./... && go build -v ./... && go test -v -coverprofile=_coverage.cov ./..."
