timeout: 3600s

options:
  env:
  - CXX=clang++
  - CGO_ENABLED=1

steps:

- name: gcr.io/cloud-builders/docker
  args: [
    "build", "-t", "testing", "-f", "Dockerfile", "."
  ]

- name: testing
  args:
  - go version
  - go vet ./...