timeout: 3600s

steps:
# Run unit tests for environment.
- name: gcr.io/$PROJECT_ID/golang-cbif:1.18
  args:
  - go version
  # - go get -v -t ./...
  - apt-get update
  - apt-get install -y --no-install-recommends clang
  # - go vet -v ./...
  # - go build -v ./...
  # - go test -v -coverprofile=_coverage.cov ./...
  # - go test -v -race ./...
  - docker run -w $GODIR -v $GOPATH/pkg/mod:/go/pkg/mod -v $PWD:$GODIR $IMAGE sh -c
    "go get -u ./... && go vet -v ./... && go build -v ./... && go test -v -coverprofile=_coverage.cov ./... && go test -v -race ./..."
  env:
  - CXX=clang++
  - CGO_ENABLED=1
  - GODIR=/go/src/github.com/m-lab/autoloader
  - IMAGE=cristinaleonr/autoloader:0