timeout: 3600s

options:
  env:
  - CXX=clang++
  - CGO_ENABLED=1

steps:

- name: gcr.io/cloud-builders/docker
  args: [
    "build", "-t", "testing", "-f", "Dockerfile", "."
  ]

- name: testing
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker run -w $GODIR -v $GOPATH/pkg/mod:/go/pkg/mod -v $PWD:$GODIR $IMAGE sh -c "go vet -v ./..."