timeout: 1800s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

steps:
- name: gcr.io/cloud-builders/docker
  id: "Build the autoloader docker image"
  args: [
    "build",
      "-t", "gcr.io/$PROJECT_ID/autoloader:${COMMIT_SHA}",
      "-f", "Dockerfile", "."
  ]

- name: gcr.io/cloud-builders/docker
  id: "Push the docker container to gcr.io"
  args: [
    "push", "gcr.io/$PROJECT_ID/autoloader:${COMMIT_SHA}",
  ]

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy the autoloader"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{COMMIT_SHA}}/'${COMMIT_SHA}'/' \
           -e 's/{{PROJECT_ID}}/'${PROJECT_ID}'/' \
           -e 's/{{MLAB_BUCKET}}/'$_MLAB_BUCKET'/' \
           -e 's/{{BUCKETS}}/'$_BUCKETS'/' \
           k8s/autoloader.yaml
    /builder/kubectl.bash apply -f k8s/autoloader.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy daily cronjob"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{AUTOLOADER_CRON_SCHEDULE}}/'0 */3 * * *'/' \
           -e 's/{{AUTOLOAD_PERIOD}}/daily/' \
           k8s/autoloader-cronjob-template.yaml > autoloader-daily-cronjob.yaml
    /builder/kubectl.bash apply -f autoloader-daily-cronjob.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing


